language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - "pip install mock"

# command to run tests
script:
  - python -m unittest discover tests
